trigger:
  branches:
    include:
      - main
      - feature/*

variables:
  - group: 'DockerCredentials'
  - name: DockerId
    value: "$(DOCKER_USERNAME)"
  - name: DockerToken
    value: "$(DOCKER_PASSWORD)"
  - name: DockerRepo
    value: "$(DOCKER_REPO)"
  - name: ServiceName
    value: "$(DOCKER_REPO)"

pool:
  vmImage: 'ubuntu-latest'

stages:

  - stage: PreBuild
    displayName: 'Pre-Build'
    jobs:
      - job: SetVersionJob
        displayName: 'Pre-Build Analysis'
        steps:
          - checkout: self
            fetchDepth: 0
            persistCredentials: true

          

          - script: |
              echo "Current directory:"
              pwd

              echo "Listing all files and folders:"
              ls -la
              chmod +x "$(Build.SourcesDirectory)/users-api/logging.sh"
              chmod +x "$(Build.SourcesDirectory)/users-api/common-script/dockerhub.sh"
            displayName: 'Make scripts executable'
          
          - script: |
              sed -i 's/\r$//' "$(Build.SourcesDirectory)/users-api/logging.sh"
              sed -i 's/\r$//' "$(Build.SourcesDirectory)/users-api/common-script/dockerhub.sh"
            displayName: 'Fix line endings in scripts'

          - script: |
              . "$(Build.SourcesDirectory)/users-api/logging.sh"
              info_msg "Run logging script"
            displayName: 'Run Logging Script'

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true

          - task: Bash@3
            name: setAppVersionStep
            displayName: 'Set APP_VERSION output variable'
            inputs:
              targetType: 'inline'
              script: |
                latest_version=$(python3 $(Build.SourcesDirectory)/users-api/get_latest_vertion.py)

                echo "latest_version=$latest_version"
                if [ -z "$latest_version" ]; then
                  echo "APP_VERSION not retrieved. Exiting"
                  exit 3
                fi

                echo "##vso[task.setvariable variable=APP_VERSION;isOutput=true]$APP_VERSION"
                echo "APP_VERSION is set to $APP_VERSION"

  - stage: BuildAndTest
    displayName: 'Project: Build and Test'
    dependsOn: PreBuild
    condition: succeeded()
    jobs:
      - job: BuildAndTest
        displayName: 'Build And Test'
        steps:
          - script: |
              echo "== Compiling project =="
              mkdir -p $(Build.ArtifactStagingDirectory)/build
              echo "Compiled app binary" > $(Build.ArtifactStagingDirectory)/build/app.bin
            displayName: 'Build Project'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)/build'
              artifactName: 'build-artifact'
              publishLocation: 'Container'
            displayName: 'Publish Build Artifact'

          - script: |
              echo "== Running Unit Tests =="
              echo "Simulating unit tests..."
              echo "All tests passed"
            displayName: 'Run Unit Tests'

  - stage: DockerBuildAndPush
    displayName: 'Docker: Build and Push'
    dependsOn: BuildAndTest
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
    variables:
      appVersion: $[ stageDependencies.PreBuild.SetVersionJob.outputs['setAppVersionStep.APP_VERSION'] ]
    jobs:
      - job: BuildAndPush
        displayName: 'Build and Push Docker Image'
        steps:
          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              containerRegistry: 'sillerolena'
              repository: 'sillerolena/lab4'
              command: 'build'
              Dockerfile: '$(Build.SourcesDirectory)/users-api/Dockerfile'   # теперь верный путь
              buildContext: '$(Build.SourcesDirectory)/users-api'
              tags: $(APP_VERSION)

          - task: Docker@2
            displayName: 'Push Docker Image'
            inputs:
              containerRegistry: 'sillerolena'
              repository: 'sillerolena/lab4'
              command: 'push'
              tags:|
              $(APP_VERSION)

  - stage: HelmChartPack
    displayName: 'Helm Chart: Pack and Push'
    dependsOn: DockerBuildAndPush
    condition: succeeded()
    jobs:
      - job: PackAndPush
        displayName: 'Pack and Push'
        steps:
          - script: |
              echo "Packing and pushing Helm chart..."
            displayName: 'Helm Chart Step'

  - stage: PostBuild
    displayName: 'Post-Build'
    dependsOn: HelmChartPack
    condition: succeeded()
    jobs:
      - job: PostBuild
        displayName: 'Post-Build'
        steps:
          - script: |
              echo "Post-build cleanup or report step"
            displayName: 'Post-Build Step'



